### PR TITLE
feat(tabs)!: use `markdown-it-container` for tabs parsing

### PR DESCRIPTION
**Pull request by DreierF**
Hi @sapphi-red,

I adjusted the syntax a little bit to be more in line with the `vuepress-plugin-element-tabs` and get rid of the error prone code that caused #10 and part of #23. To make that work I had to introduce a separate `PluginTabsTab` component instead of the dynamic slots to collect the label/content mapping incrementally.

I'm not super familiar with Vue so if you know a better solution I'm open for suggestions.

### CODE REVIEW

**Comment by sapphi-red** [comment]
- Would you split the dep version bumps to another PR?
- I'm fine with changing the syntax. But I prefer the syntax to omit the `:::` for the tab close.
  ```
  ::::tabs
  ::: a
  a content

  ::: b
  b content
  ::::
  ```
  Would you implement this? If not, I can try.

**Comment by DreierF** [comment]
Sure, I removed the version bumps from the PR.

Requiring the `:::` is actually what I mainly meant with syntax change. I don't have a good idea of how you could reliably parse the version without closing fences, while still allowing arbitrary Markdown content in between.

**Comment by sapphi-red** [comment]
I pushed the implementation for the syntax I proposed (I tweak the syntax a bit though).
```
:::tabs
== tab name 1
== tab name 2
:::
```
Would you take a look if this one works for you too?

**Comment by DreierF** [comment]
Thanks! Works like a charm 🙂

**Pull request merged**
